# Generated by Django 5.1.6 on 2025-02-27 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Bonds', 'Bonds'), ('Lloyds', 'Lloyds'), ('Savings', 'Savings'), ('Investment', 'Investment'), ('Lloyds Savings', 'Lloyds Savings'), ('Cash ISA', 'Cash ISA'), ('Monzo', 'Monzo'), ('Stock Trading 212', 'Stock Trading 212'), ('Ελλάδα', 'Ελλάδα'), ('Επενδύσεις', 'Επενδύσεις'), ('Credit Card', 'Credit Card'), ('Total', 'Total')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
        ),
    ]
