# Generated by Django 5.1.6 on 2025-03-01 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_latest_balance_alter_account_name_and_more'),
    ]

    operations = [
    ]
