# Generated by Django 5.1.6 on 2025-03-05 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_notification_is_read_alter_notification_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='currency',
            field=models.CharField(choices=[('€', 'Euro (€)'), ('$', 'Dollar ($)'), ('£', 'Pound (£)')], default='€', max_length=1),
        ),
    ]
