# Generated by Django 6.0.4 on 2026-04-25 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_account_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="currency",
            field=models.CharField(
                choices=[
                    ("GBP", "Pound (£)"),
                    ("EUR", "Euro (€)"),
                    ("USD", "Dollar ($)"),
                ],
                default="GBP",
                max_length=3,
            ),
        ),
    ]
