# Generated by Django 6.0.4 on 2026-04-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="notes",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="reminder_day",
            field=models.CharField(
                choices=[
                    ("1", "1"),
                    ("2", "2"),
                    ("3", "3"),
                    ("4", "4"),
                    ("5", "5"),
                    ("6", "6"),
                    ("7", "7"),
                    ("8", "8"),
                    ("9", "9"),
                    ("10", "10"),
                    ("11", "11"),
                    ("12", "12"),
                    ("13", "13"),
                    ("14", "14"),
                    ("15", "15"),
                    ("16", "16"),
                    ("17", "17"),
                    ("18", "18"),
                    ("19", "19"),
                    ("20", "20"),
                    ("21", "21"),
                    ("22", "22"),
                    ("23", "23"),
                    ("24", "24"),
                    ("25", "25"),
                    ("26", "26"),
                    ("27", "27"),
                    ("28", "28"),
                    ("last", "Last day of month"),
                ],
                default="1",
                max_length=4,
            ),
        ),
    ]
