# Generated by Django 6.0.4 on 2026-04-29 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_transaction_notes_alter_userprofile_reminder_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="privacy_mode",
            field=models.BooleanField(default=False),
        ),
    ]
