# Generated by Django 6.0.4 on 2026-04-29 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_userprofile_privacy_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="icon",
            field=models.CharField(default="🏦", max_length=10),
        ),
    ]
