# Generated by Django 6.0.4 on 2026-04-29 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_account_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
