# Generated by Django 6.0.4 on 2026-04-29 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_account_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="show_icons",
            field=models.BooleanField(default=True),
        ),
    ]
