# Generated by Django 6.0.4 on 2026-05-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_userprofile_email_verified_emailverificationtoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("savings", "Savings"),
                    ("investment", "Investment"),
                    ("property", "Property"),
                    ("pension", "Pension"),
                    ("debt", "Debt / Mortgage"),
                    ("asset", "Asset"),
                    ("other", "Other"),
                ],
                default="savings",
                max_length=20,
            ),
        ),
    ]
