# Generated by Django 6.0.4 on 2026-05-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_account_account_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="target",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
