# Generated by Django 6.0.4 on 2026-09-02 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_account_target"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
    ]
